# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfacefBqcJM.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QLCDNumber,
    QLabel, QPushButton, QSizePolicy, QWidget)
import mode_rc
import fan_auto_rc
import power_rc
import filter_rc
import display_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(718, 646)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(129, 129, 129, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush3 = QBrush(QColor(255, 255, 220, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush3)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush2)
        brush4 = QBrush(QColor(255, 255, 255, 127))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush2)
        brush5 = QBrush(QColor(0, 0, 0, 127))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush2)
        Form.setPalette(palette)
        Form.setStyleSheet(u"background-color: rgb(129, 129, 129);")
        self.label_touch_filter = QLabel(Form)
        self.label_touch_filter.setObjectName(u"label_touch_filter")
        self.label_touch_filter.setGeometry(QRect(260, 90, 91, 31))
        self.label_touch_mode = QLabel(Form)
        self.label_touch_mode.setObjectName(u"label_touch_mode")
        self.label_touch_mode.setGeometry(QRect(40, 90, 91, 31))
        self.label_touch_display = QLabel(Form)
        self.label_touch_display.setObjectName(u"label_touch_display")
        self.label_touch_display.setGeometry(QRect(140, 90, 121, 31))
        self.label_touch_power = QLabel(Form)
        self.label_touch_power.setObjectName(u"label_touch_power")
        self.label_touch_power.setGeometry(QRect(370, 90, 121, 31))
        self.lcdNumber_aqi_index = QLCDNumber(Form)
        self.lcdNumber_aqi_index.setObjectName(u"lcdNumber_aqi_index")
        self.lcdNumber_aqi_index.setGeometry(QRect(43, 130, 81, 61))
        self.lcdNumber_aqi_index.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_aqi_index.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_rpm = QLCDNumber(Form)
        self.lcdNumber_rpm.setObjectName(u"lcdNumber_rpm")
        self.lcdNumber_rpm.setGeometry(QRect(160, 130, 81, 61))
        self.lcdNumber_rpm.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_rpm.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_fan_speed = QLCDNumber(Form)
        self.lcdNumber_fan_speed.setObjectName(u"lcdNumber_fan_speed")
        self.lcdNumber_fan_speed.setGeometry(QRect(270, 130, 81, 61))
        self.lcdNumber_fan_speed.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_fan_speed.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_filter_time = QLCDNumber(Form)
        self.lcdNumber_filter_time.setObjectName(u"lcdNumber_filter_time")
        self.lcdNumber_filter_time.setGeometry(QRect(380, 130, 81, 61))
        self.lcdNumber_filter_time.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_filter_time.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(540, 20, 161, 31))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_port_name = QLabel(self.layoutWidget)
        self.label_port_name.setObjectName(u"label_port_name")

        self.horizontalLayout.addWidget(self.label_port_name)

        self.comboBox_port = QComboBox(self.layoutWidget)
        self.comboBox_port.setObjectName(u"comboBox_port")
        self.comboBox_port.setStyleSheet(u"font: 700 12pt \"\ub9d1\uc740 \uace0\ub515\";\n"
"color: rgb(0, 0, 0);")

        self.horizontalLayout.addWidget(self.comboBox_port)

        self.pushButton_open = QPushButton(Form)
        self.pushButton_open.setObjectName(u"pushButton_open")
        self.pushButton_open.setGeometry(QRect(500, 350, 141, 71))
        self.pushButton_open.setStyleSheet(u"background-color: rgb(85, 255, 255);")
        self.lcdNumber_command_status = QLCDNumber(Form)
        self.lcdNumber_command_status.setObjectName(u"lcdNumber_command_status")
        self.lcdNumber_command_status.setGeometry(QRect(620, 130, 81, 61))
        self.lcdNumber_command_status.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_command_status.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber_temperature = QLCDNumber(Form)
        self.lcdNumber_temperature.setObjectName(u"lcdNumber_temperature")
        self.lcdNumber_temperature.setGeometry(QRect(510, 130, 81, 61))
        self.lcdNumber_temperature.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_temperature.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.label_touch_filter_2 = QLabel(Form)
        self.label_touch_filter_2.setObjectName(u"label_touch_filter_2")
        self.label_touch_filter_2.setGeometry(QRect(500, 90, 91, 31))
        self.label_touch_power_2 = QLabel(Form)
        self.label_touch_power_2.setObjectName(u"label_touch_power_2")
        self.label_touch_power_2.setGeometry(QRect(610, 90, 101, 31))
        self.label_touch_mode_2 = QLabel(Form)
        self.label_touch_mode_2.setObjectName(u"label_touch_mode_2")
        self.label_touch_mode_2.setGeometry(QRect(40, 200, 91, 31))
        self.lcdNumber_aqi_grade = QLCDNumber(Form)
        self.lcdNumber_aqi_grade.setObjectName(u"lcdNumber_aqi_grade")
        self.lcdNumber_aqi_grade.setGeometry(QRect(40, 240, 81, 61))
        self.lcdNumber_aqi_grade.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_aqi_grade.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.label_touch_power_3 = QLabel(Form)
        self.label_touch_power_3.setObjectName(u"label_touch_power_3")
        self.label_touch_power_3.setGeometry(QRect(150, 200, 101, 31))
        self.lcdNumber_status = QLCDNumber(Form)
        self.lcdNumber_status.setObjectName(u"lcdNumber_status")
        self.lcdNumber_status.setGeometry(QRect(160, 240, 81, 61))
        self.lcdNumber_status.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_status.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.label_touch_power_4 = QLabel(Form)
        self.label_touch_power_4.setObjectName(u"label_touch_power_4")
        self.label_touch_power_4.setGeometry(QRect(260, 200, 151, 31))
        self.lcdNumber_led_brightness = QLCDNumber(Form)
        self.lcdNumber_led_brightness.setObjectName(u"lcdNumber_led_brightness")
        self.lcdNumber_led_brightness.setGeometry(QRect(300, 240, 81, 61))
        self.lcdNumber_led_brightness.setStyleSheet(u"font: 14pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lcdNumber_led_brightness.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.label_fw_version = QLabel(Form)
        self.label_fw_version.setObjectName(u"label_fw_version")
        self.label_fw_version.setGeometry(QRect(477, 250, 201, 41))
        self.layoutWidget.raise_()
        self.label_touch_filter.raise_()
        self.label_touch_mode.raise_()
        self.label_touch_display.raise_()
        self.label_touch_power.raise_()
        self.lcdNumber_aqi_index.raise_()
        self.lcdNumber_rpm.raise_()
        self.lcdNumber_fan_speed.raise_()
        self.lcdNumber_filter_time.raise_()
        self.pushButton_open.raise_()
        self.lcdNumber_command_status.raise_()
        self.lcdNumber_temperature.raise_()
        self.label_touch_filter_2.raise_()
        self.label_touch_power_2.raise_()
        self.label_touch_mode_2.raise_()
        self.lcdNumber_aqi_grade.raise_()
        self.label_touch_power_3.raise_()
        self.lcdNumber_status.raise_()
        self.label_touch_power_4.raise_()
        self.lcdNumber_led_brightness.raise_()
        self.label_fw_version.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_touch_filter.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Fan Speed</span></p></body></html>", None))
        self.label_touch_mode.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">AQI Index</span></p></body></html>", None))
        self.label_touch_display.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">RPM</span></p></body></html>", None))
        self.label_touch_power.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Filter used time</span></p></body></html>", None))
        self.label_port_name.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Port :</span></p></body></html>", None))
        self.pushButton_open.setText(QCoreApplication.translate("Form", u"OPEN", None))
        self.label_touch_filter_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Temp</span></p></body></html>", None))
        self.label_touch_power_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">CMD status</span></p></body></html>", None))
        self.label_touch_mode_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">AQI grade</span></p></body></html>", None))
        self.label_touch_power_3.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Status</span></p></body></html>", None))
        self.label_touch_power_4.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">LED Brightness</span></p></body></html>", None))
        self.label_fw_version.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">FW version</span></p></body></html>", None))
    # retranslateUi

